@endpoint = http://localhost:{{$dotenv PORT}}

### Create new league
POST {{ endpoint }}/newleague 
content-type: application/json

{
  "id": "mpg_league_9",
  "name": "ligue 5",
  "description": "bof cette ligue",
  "adminId": "user_1"
}

### Update second team name
PATCH {{ endpoint }}/2
Content-Type: application/json

{
  "name": "la team de jojo"
}